// flow-typed signature: 065bb18ceed318461144f3bf9c0dfc7a
// flow-typed version: <<STUB>>/mocha_vx.x.x/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mocha'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mocha' {
  declare module.exports: any;
}
